/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNI_HelloJNI */

#ifndef _Included_JNI_HelloJNI
#define _Included_JNI_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNI_HelloJNI
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNI_HelloJNI_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
